# 变量
@url = http://localhost:3001/api  
@json = Content-Type: application/json

### 
get {{url}}

### 获取所有用户
get {{url}}/users


### 注册
post {{url}}/register
{{json}}

{
  "username":"user1",
  "password":"12345"
}

### 登陆
post {{url}}/login
{{json}}

{
  "username":"user",
  "password":"12345"
}


### 
get {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkODlhZTBjZWZjYzc3MjFhNDk3MGNiZiIsImlhdCI6MTU2OTMwNDk3Mn0.6ruZFjRmhyuSw-p2rtPah0u6ZjvRblPVD3b9XcD0ruE

